### PR TITLE
Add save and remove commands

### PR DESCRIPTION
**Pull request by kovetskiy**
This changeset will allow to like and unlike current playing song. The API was
implemented already, so I've just added cmd commands.

### CODE REVIEW

**Comment by kovetskiy** [comment]
It also fixes #24.

**Comment by kovetskiy** [comment]
@MarinPostma it would be cool if you could test it. It works for me, though

Here is how you can run my fork on your machine:

```
$  GOPATH=/tmp/baton-fork
$  go get github.com/joshuathompson/baton
$  cd $GOPATH/src/github.com/joshuathompson/baton
$ git remote set-url origin https://github.com/kovetskiy/baton
$ git pull origin master
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 3), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (6/6), done.
From github.com:kovetskiy/baton
 * branch            master     -> FETCH_HEAD
   804a717..196c866  master     -> origin/master
Updating 804a717..196c866
Fast-forward
 .gitignore    |  1 +
 cmd/remove.go | 39 +++++++++++++++++++++++++++++++++++++++
 cmd/save.go   | 39 +++++++++++++++++++++++++++++++++++++++
 3 files changed, 79 insertions(+)
 create mode 100644 cmd/remove.go
 create mode 100644 cmd/save.go
$ go build
```

Then just check it with ./baton save & ./baton remove

**Comment by MarinPostma** [comment]
@kovetskiy This does not work for me, the `save` and `remove` commands are not found. This is my `git log` output: 
```
commit 196c8665e3d0d4db4fc557e4f1fc7d120d8a0a59 (HEAD -> master, origin/master, origin/HEAD)
Author: Egor Kovetskiy <e.kovetskiy@gmail.com>
Date:   Fri Jul 19 16:19:36 2019 +0300

    add save & remove commands
```

i tried builing with `go build` and `make linux`.

**Comment by kovetskiy** [comment]
Are you sure you run local build instance of ./baton and not what you already have installed in your system?

**Comment by joshuathompson** [comment]
Works for me, thanks for the contribution 👍

**Pull request merged**
